name: Build, Test & Push to ECR

on:
  push:
    branches:
      - main

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r 'Lab 2/requirements.txt'

      - name: Import sanity check
        run: |
          python -c "import pandas, sklearn, joblib, litestar"

      - name: Validate ML model files
        run: |
          python -c "import joblib; joblib.load('Lab 2/data/rf_model.pkl')"
          python -c "import joblib; joblib.load('Lab 2/data/column_transformer.pkl')"
          
      - name: Debug path
        run: |
            cd "Lab 2" 
            pwd
            ls -R
            
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        
      - name: Build Docker image
        run: |
          cd "Labs 2"
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/churn-api:latest .
      
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/churn-api:latest

     
      
